config/routes.rb
Rails.application.routes.draw do
  root 'appointments#index'
  resources :appointments
  resources :physicians
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  validates :patient, :physician_id, :date, :time, presence: true
  validates :time, uniqueness: { scope: :physician }
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  validates :first_name, :specialty, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
    @physicians = Physician.all
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to root_path, notice: "Запись создана"
    else
      render 'new'
    end
  end

  def edit
    @appointment = Appointment.find(params[:id])
  end

  def update
    @appointment = Appointment.find(params[:id])
    if @appointment.update(appointment_params)
      redirect_to root_url, notice: "Карточка обновлена"
    else
      render 'edit'
    end
  end

  def show
    @appointment = Appointment.find(params[:id])
  end

  private

  def appointment_params
    params.require(:appointment).permit(:physician_id, :date, :time, :patient)
  end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  def new
    @physician = Physician.new
  end

  def create
    @physician = Physician.new(physician_params)
    
    if @physician.save
      redirect_to root_path "Карточка врача создана."
    else
      render 'new'
    end
  end

  def edit
    @physician = Physician.find(params[:id])
  end

  def update
    @physician = Physician.find(params[:id])
    if @physician.update(physician_params)
      redirect_to physicians_path, notice: "Карточка обновлена"
    else
      render 'edit'
    end
  end

  def index
    @physicians = Physician.all
  end

  def show
    @physician = Physician.find(params[:id]) 
  end

  private
  
  def physician_params
    params.require(:physician).permit(:first_name, :last_name, :specialty)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/views/appointments/_form.html.erb
<%= form_for @appointment do |form| %>
  <% if @appointment.errors.any? %>
          <ul>
            <% @appointment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
  <% end %>

  <%= form.label :physician_id, "Врач" %>
  <%= form.select(:physician_id, [["Терапевт", '1'], ["Лор", '2'], ["Иммунолог", '3']]) %>
  
  <%= form.label :patient %>
  <%= form.text_field :patient %>

  <%= form.label :date %>
  <%= form.date_select(:date, order: [:year, :month, :day])%>

  <%= form.label :time %>
  <%= form.select(:time, [['9-00'], ['10-00'], ['11-00'], ['12-00'], ['14-00'], ['15-00'], ['16-00'], ['17-00']]) %>
  
  <%= form.submit "Сохранить" %>
<% end %>

app/views/appointments/edit.html.erb
<h1>Редактировать запись</h1>
<%= render 'form' %>
<%= link_to 'Вернуться н аглавную', root_path %>

app/views/appointments/index.html.erb
<h1>Записать к врачу</h1>

<% @physicians.each do |a| %>
  <ul>
    <li><%= a.first_name %> <%= a.last_name %></li>
    <li><%= a.specialty %></li>
    <% a.appointments.each do |f| %>
      <ul>
        <li>Время: <%= f.time %></li>
        <li>Дата: <%= f.date %></li>
        <li>Пациент: <%= f.patient %></li>
      </ul>
      <%= link_to "Редактировать запись", edit_appointment_path(f.id) %>
    <% end %>
  </ul> 
<% end %>
<p>
  <%= link_to "Создать запись", new_appointment_path %>
</p>
<p>
  <%= link_to "Создать карточку врача", new_physician_path %>
</p>
<p>
  <%= link_to "Наши врачи", physicians_path %>
</p>

app/views/appointments/new.html.erb
<h1>Запись</h1>

<%= render 'form' %>

<%= link_to 'Вернуться н аглавную', root_path %>

app/views/appointments/show.html.erb
<h1>Запись</h1>
<p>
  <%= link_to 'Вернуться н аглавную', root_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hospital</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/physicians/_form.html.erb
<%= form_for(@physician) do |f| %>
  <%= f.label :first_name, "Имя" %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name, "Фамилия"%>
  <%= f.text_field :last_name %>

  <%= f.label :specialty, "Специализация" %>
  <%= f.text_field :specialty %>

  <%= f.submit "Сохранить"%>
<% end %>

app/views/physicians/edit.html.erb
<h1>Редактировать  карточку врача</h1>

<%= render 'form' %>

<%= link_to 'Вернуться н аглавную', root_path %>

app/views/physicians/index.html.erb
<h1>Карточки врачей</h1>

<% @physicians.each do |p| %>
  <ul>
    <li><%= p.first_name %> <%= p.last_name %></li>
    <li><%= p.specialty %></li>
  </ul>
  <%= link_to "Редактировать", edit_physician_path(p.id) %>
<% end %>
<p>
  <%= link_to "Вернуться на главную", root_path %>
</p>

app/views/physicians/new.html.erb
<h1>Создать карточку врача:</h1>

<%= render 'form' %>

<%= link_to "Вернуться на главную", root_path %>

app/views/physicians/show.html.erb
<h1>Карточка врача</h1>
<ul>
  <li><%= @physician.first_name %> <%= @physician.last_name %></li>
  <li><%= @physician.specialty %></li>
</ul>
<%= link_to "Вернуться на главную", root_path %>